### ISSUE TITLE
Passport Authentication Due-Jan16

### ISSUE THREAD

**Issue by adpir** [DaronSchmit/DinnerAndAMovie#12]
We need to condense the passport authentication files to handlebars. The Passport Authentication has three HTML files. The HTML  files example you can find it in the Reverse Engineering Homework we have for this coming week. 

1. login.HTML
2. Signup.HTML
3. Member.HTML

 @suhirsaleh, Can you  try to do handlebars instead of having three separate HTML files?

**Comment by Kay0s** [comment]
member-block - conditional if signed in or not signed in

**Comment by Kay0s** [comment]
moved to mvp +
