### ISSUE TITLE
Create Framework of App Interface/Flow

### ISSUE THREAD

**Issue by Kay0s** [DaronSchmit/DinnerAndAMovie#3]

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/104681917-179c7480-56b9-11eb-9a75-6565b8148ca0.png)

**Comment by Kay0s** [comment]
@DaronSchmit and @suhirsaleh what are your thoughts on the app frameworK?

**Comment by adpir** [comment]
![aww-board](https://user-images.githubusercontent.com/69180791/104798178-ae8d2d80-579a-11eb-82f9-2360c092c1b8.png)

**Comment by adpir** [comment]
@DaronSchmit  @suhirsaleh  @Kay0s what are your thoughts on the app frameworK?

**Comment by Kay0s** [comment]
@adpir Fun user interface!  Thanks for mocking up the flow.

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/104818099-14090a80-57eb-11eb-99b1-77790c21ab04.png)

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/104818110-25521700-57eb-11eb-88ab-60239d7c4d50.png)

**Comment by Kay0s** [comment]
![image](https://user-images.githubusercontent.com/71153831/104821117-46bcfe00-57ff-11eb-8ca4-69ca6ff077e6.png)

**Comment by Kay0s** [comment]
Also add link for previously viewed movies and foods.
