### ISSUE TITLE
Code need Review from the team

### ISSUE THREAD

**Issue by adpir** [DaronSchmit/DinnerAndAMovie#44]
Took screenshoots of some discrepancies in the code.  
<img width="1071" alt="Screen Shot 2021-01-21 at 1 44 26 AM" src="https://user-images.githubusercontent.com/69180791/105301057-59358f80-5b91-11eb-98d7-e26ae8255541.png">
<img width="1071" alt="Screen Shot 2021-01-21 at 1 44 44 AM" src="https://user-images.githubusercontent.com/69180791/105301112-5c308000-5b91-11eb-8bb7-a21e22a845f3.png">
<img width="1239" alt="Screen Shot 2021-01-21 at 1 46 29 AM" src="https://user-images.githubusercontent.com/69180791/105301128-5d61ad00-5b91-11eb-85b4-4f19a787ad67.png">
<img width="1182" alt="Screen Shot 2021-01-21 at 1 47 29 AM" src="https://user-images.githubusercontent.com/69180791/105301139-5d61ad00-5b91-11eb-80ff-39ef78ff9ea5.png">
<img width="1009" alt="Screen Shot 2021-01-21 at 1 49 26 AM" src="https://user-images.githubusercontent.com/69180791/105301146-5dfa4380-5b91-11eb-9540-6a5f60b59c27.png">

Need to review with the team to see If something need to be updated

**Comment by Kay0s** [comment]
@adpir Thanks for bringing this to our attention.  Let's review tonight in class.
